### ISSUE TITLE
Error The method mapWidgetInitiated(MapWidget) of type new GoogleMapInitListener(){} must override or implement a supertype method

### ISSUE THREAD

**Issue by Tapsprofile** [tjkaal/google-maps-streetview-extension#1]
Hi Team,

Please find the issues..
The method mapWidgetInitiated(MapWidget) of type new GoogleMapInitListener(){} must override or implement a supertype method

Thanks,
Taps

**Comment by tapioaali** [comment]
What? Where are you getting this error? Are you using the latest version of both Google Maps add-on and Street View Extension?

**Comment by tapioaali** [comment]
There was a typo in the sources. In case you were checking out the project directly, you could have met some errors. But please elaborate, what are you actually trying to do and what are the version numbers of both Google Maps Add-on and Street View Extension?

**Comment by tapioaali** [comment]
Closing this as more info has not been given by the reporter. Please reopen with answers to my questions if the problem persists.
